spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/danda_db
    username: postgres
    password: 921
    driver-class-name: org.postgresql.Driver

application:
  security:
    jwt:
      secret-key: 87b32c1d6aac4301897918ff99ef3c498d524bfdded2dc6f3aafea1ffc5d64b8
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
